### ISSUE TITLE
short year unexpected format

### ISSUE THREAD

**Issue by RafaelC457ro** [thiamsantos/vanilla-commons#14]
Bug:
short year unexpected format

### Expected Behavior

```js
const {formatDate} = require('vanilla-commons')

const formated = formatDate('{DD}{MM}{YY}',new Date('July 10, 2017 14:56:00'))
\\ expect to be  '100717'
console.log(formated)
```
### Current Behavior

```js
const {formatDate} = require('vanilla-commons')

const formated = formatDate('{DD}{MM}{YY}',new Date('July 10, 2017 14:56:00'))
\\ result '1007117'
console.log(formated)
```
### Your Environment

| software         | version(s)
| ---------------- | -------
| vanilla-commons  | 1.0.0
| node             | v7.8.0
| npm              | 5.1.0
| Operating System | Linux Ubuntu 16.04

**Comment by thiamsantos** [comment]
That's happening because I was using the deprecated method [getYear](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Date/getYear). I will fix that soon.
