### ISSUE TITLE
unexpected day variation in parseDate

### ISSUE THREAD

**Issue by RafaelC457ro** [thiamsantos/vanilla-commons#17]
Bug: ParseDate produce a different day value.

### Expected Behavior

```js
import {parseDate} from 'vanilla-commons'

parseDate('{DD}{MM}{YY}','110412')
// 2012-04-11T03:00:00.000Z
// brazil timezone midnight
```
### Current Behavior

```js
import {parseDate} from 'vanilla-commons'

parseDate('{DD}{MM}{YY}','110412')
// 2012-04-12T00:00:00.000Z
//          ^ some different value here
```
### Context

I trying to parse a date from a file that give only this date format, and i can't test this properly, because always produce a different value.
### Your Environment

| software         | version(s)
| ---------------- | -------
| vanilla-commons  | 1.1.0
| node             | v7.8.0
| npm              | 5.3.0
| Operating System | Ubuntu 16.04.2 LTS

**Comment by thiamsantos** [comment]
The issue was solved? I was not able to reproduce it.
